CREATE TABLE IF NOT EXISTS LLM_EXTRACT_RUN (
    RUN_ID BIGINT NOT NULL AUTO_INCREMENT,
    PROCESS_TYPE VARCHAR(50) NOT NULL,
    TRANSFER_YEAR VARCHAR(4) NULL,
    PROD_YEAR VARCHAR(4) NULL,
    RETRY_FAIL CHAR(1) NOT NULL DEFAULT 'N',
    BATCH_SIZE INT NULL,
    MAX_LOOP INT NULL,
    LOOP_COUNT INT NOT NULL DEFAULT 0,
    STATUS VARCHAR(20) NOT NULL,
    STARTED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ENDED_AT DATETIME(3) NULL,
    TOTAL_TARGET_COUNT INT NOT NULL DEFAULT 0,
    TOTAL_SUCCESS_COUNT INT NOT NULL DEFAULT 0,
    TOTAL_FAIL_COUNT INT NOT NULL DEFAULT 0,
    ERROR_MSG TEXT NULL,
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (RUN_ID),
    KEY IDX_LLM_EXTRACT_RUN_STARTED_AT (STARTED_AT),
    KEY IDX_LLM_EXTRACT_RUN_STATUS (STATUS),
    KEY IDX_LLM_EXTRACT_RUN_PROCESS_DATE (PROCESS_TYPE, STARTED_AT),
    KEY IDX_LLM_EXTRACT_RUN_TARGET (TRANSFER_YEAR, PROD_YEAR, PROCESS_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS LLM_EXTRACT_ITEM_LOG (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT,
    RUN_ID BIGINT NOT NULL,
    SUBJECT_TYPE VARCHAR(20) NOT NULL,
    RC_CODE VARCHAR(50) NULL,
    RC_RFILE_NO VARCHAR(50) NULL,
    RC_RITEM_NO VARCHAR(50) NULL,
    STATUS VARCHAR(20) NOT NULL,
    ERROR_MSG TEXT NULL,
    ORG_NM VARCHAR(500) NULL,
    PROD_YEAR VARCHAR(4) NULL,
    GOV_TASK_NO VARCHAR(500) NULL,
    GOV_TASK_NM VARCHAR(500) NULL,
    DETAIL_TASK_CD VARCHAR(50) NULL,
    DETAIL_TASK_NM VARCHAR(100) NULL,
    MATCHING_TERMS  VARCHAR(500) NULL,
    MATCHING_SOURCE VARCHAR(100) NULL,
    CRITERIA_TYPE VARCHAR(100) NULL,
    DECISION_VALUE VARCHAR(50) NULL,
    DECISION_REASON VARCHAR(500) NULL,
    REVIEW_EXCLUDE_REASON VARCHAR(500) NULL,
    RESULT_JSON JSON NULL,
    PROCESSED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (LOG_ID),
    KEY IDX_LLM_EXTRACT_ITEM_LOG_RUN (RUN_ID),
    KEY IDX_LLM_EXTRACT_ITEM_LOG_DATE (PROCESSED_AT),
    KEY IDX_LLM_EXTRACT_ITEM_LOG_DASHBOARD (SUBJECT_TYPE, STATUS, PROCESSED_AT),
    KEY IDX_LLM_EXTRACT_ITEM_LOG_RECORD (RC_CODE, RC_RFILE_NO, RC_RITEM_NO),
    CONSTRAINT FK_LLM_EXTRACT_ITEM_LOG_RUN
    FOREIGN KEY (RUN_ID) REFERENCES LLM_EXTRACT_RUN (RUN_ID)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS ORG_NM VARCHAR(500) NULL AFTER ERROR_MSG;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS PROD_YEAR VARCHAR(4) NULL AFTER ORG_NM;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS GOV_TASK_NO VARCHAR(500) NULL AFTER PROD_YEAR;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS GOV_TASK_NM VARCHAR(500) NULL AFTER GOV_TASK_NO;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS DETAIL_TASK_CD VARCHAR(50) NULL AFTER GOV_TASK_NM;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS DETAIL_TASK_NM VARCHAR(100) NULL AFTER DETAIL_TASK_CD;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS MATCHING_TERMS VARCHAR(500) NULL AFTER DETAIL_TASK_NM;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS MATCHING_SOURCE VARCHAR(100) NULL AFTER MATCHING_TERMS;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS CRITERIA_TYPE VARCHAR(100) NULL AFTER MATCHING_SOURCE;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS DECISION_VALUE VARCHAR(50) NULL AFTER CRITERIA_TYPE;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS DECISION_REASON VARCHAR(500) NULL AFTER DECISION_VALUE;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS REVIEW_EXCLUDE_REASON VARCHAR(500) NULL AFTER DECISION_REASON;
ALTER TABLE LLM_EXTRACT_ITEM_LOG ADD COLUMN IF NOT EXISTS RESULT_JSON JSON NULL AFTER REVIEW_EXCLUDE_REASON;