CREATE TABLE IF NOT EXISTS TB_RECORD_CONTENT_CHUNK (
    CHUNK_ID BIGINT NOT NULL AUTO_INCREMENT,
    EXTRACT_IDX BIGINT NOT NULL,
    RC_RFILE_NO VARCHAR(50) NOT NULL,
    RC_RITEM_NO VARCHAR(50) NOT NULL,
    FILE_NAME VARCHAR(500) NOT NULL,
    ZIP_ENTRY_FILE_NAME VARCHAR(500) NULL,
    ZIP_SEQ INT NULL,
    CHUNK_SEQ INT NOT NULL,
    DOC_ROLE VARCHAR(30) NOT NULL,
    DOC_TYPE VARCHAR(30) NOT NULL,
    SECTION_PATH VARCHAR(1000) NULL,
    LAW_CHAPTER VARCHAR(500) NULL,
    LAW_SECTION VARCHAR(500) NULL,
    LAW_ARTICLE_NO VARCHAR(50) NULL,
    LAW_ARTICLE_TITLE VARCHAR(1000) NULL,
    LAW_ARTICLE_CONTENT TEXT NULL,
    CHUNK_TEXT MEDIUMTEXT NOT NULL,
    START_OFFSET INT NULL,
    END_OFFSET INT NULL,
    CHAR_COUNT INT NULL,
    TOKEN_COUNT INT NULL,
    CHUNK_STATUS VARCHAR(20) NOT NULL DEFAULT 'READY',
    ERROR_MSG TEXT NULL,
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CHUNK_ID),
    KEY IDX_RECORD_CONTENT_CHUNK_EXTRACT (EXTRACT_IDX),
    KEY IDX_RECORD_CONTENT_CHUNK_RECORD (RC_RFILE_NO, RC_RITEM_NO),
    KEY IDX_RECORD_CONTENT_CHUNK_FILE (FILE_NAME(191), ZIP_SEQ),
    KEY IDX_RECORD_CONTENT_CHUNK_DOC_SEQ (EXTRACT_IDX, CHUNK_SEQ),
    KEY IDX_RECORD_CONTENT_CHUNK_TYPE (DOC_ROLE, DOC_TYPE),
    KEY IDX_RECORD_CONTENT_CHUNK_LAW (LAW_ARTICLE_NO),
    KEY IDX_RECORD_CONTENT_CHUNK_STATUS (CHUNK_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE TB_RECORD_CONTENT_CHUNK
    ADD COLUMN IF NOT EXISTS EXTRACT_IDX BIGINT NULL AFTER CHUNK_ID;

CREATE INDEX IF NOT EXISTS IDX_RECORD_CONTENT_CHUNK_EXTRACT
    ON TB_RECORD_CONTENT_CHUNK (EXTRACT_IDX);

ALTER TABLE TB_RECORD_CONTENT_CHUNK
    ADD COLUMN IF NOT EXISTS LAW_CHAPTER VARCHAR(500) NULL AFTER SECTION_PATH,
    ADD COLUMN IF NOT EXISTS LAW_SECTION VARCHAR(500) NULL AFTER LAW_CHAPTER,
    ADD COLUMN IF NOT EXISTS LAW_ARTICLE_NO VARCHAR(50) NULL AFTER LAW_SECTION,
    ADD COLUMN IF NOT EXISTS LAW_ARTICLE_TITLE VARCHAR(1000) NULL AFTER LAW_ARTICLE_NO,
    ADD COLUMN IF NOT EXISTS LAW_ARTICLE_CONTENT TEXT NULL AFTER LAW_ARTICLE_TITLE;

CREATE INDEX IF NOT EXISTS IDX_RECORD_CONTENT_CHUNK_LAW
    ON TB_RECORD_CONTENT_CHUNK (LAW_ARTICLE_NO);
